// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"sealion/application/usecase"
	"sealion/config"
	"sealion/domain/service"
	"sealion/infrastructure/persistence/datastore"
	"sealion/interfaces/handler"
)

// Injectors from wire.go:

func initialize() (handler.TaskHandler, error) {
	db, err := config.GetDbConn()
	if err != nil {
		return nil, err
	}
	taskRepository := datastore.NewTaskRepository(db)
	jiraClient, err := config.NewJiraClient()
	if err != nil {
		return nil, err
	}
	taskService := service.NewTaskService(jiraClient)
	taskUseCase := usecase.NewTaskUseCase(taskRepository, taskService)
	taskHandler := handler.NewTaskHandler(taskUseCase)
	return taskHandler, nil
}
